module.exports = () => { 
    const shopPieces=[
      { id:'1',type: 'clothe',size: 's',gender: 'man', typeClothe: 'shirt',price:'3000',location: 'img1.png'},
      { id:'2',type: 'clothe',size: 's',gender: 'man', typeClothe: 'cropeTop',price:'3000',location: 'img2.png'},
      { id:'3',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img6.png'},
      { id:'4',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: 'img9.png'},
      { id:'6',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: 'img7.png'},
      { id:'7',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: 'img8.png'},
      { id:'8',type: 'clothe',size: 'm',gender: 'woman', typeClothe: 'shirt',price:'3000',location: 'img10.png'},
      { id:'10',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img11.png'},
      { id:'11',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img12.png'},
      { id:'12',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img13.png'},
      { id:'13',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img14.png'},
      { id:'14',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img15.png'},
      { id:'15',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img16.png'},
      // { id:'16',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img17.png'},
      // { id:'17',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img18.png'},
      // { id:'18',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img19.png'},
      { id:'19',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'sweatshirt',price:'3000',location: 'img3.png'},
      { id:'20',type: 'clothe',size: 'l',gender: 'woman', typeClothe: 'cropeTop',price:'3000',location: 'img4.png'},
      { id:'21',type: 'clothe',size: 'l', gender: 'woman', typeClothe: 'cropeTop',price:'3000',location: 'img5.png'},
      { id:'23',type: 'wop',name: 'Spring4',price:'3000',location: 'img34.jpeg'},
      { id:'24',type: 'wop',name: 'Spring4',price:'3000',location: 'img35.jpeg'},
      { id:'25',type: 'wop',name: 'Spring4',price:'3000',location: 'img37.jpeg'},
      { id:'26',type: 'wop',name: 'Spring4',price:'3000',location: 'img38.jpeg'},
      { id:'27',type: 'wop',name: 'Spring4',price:'3000',location: 'img39.jpeg'},
      { id:'28',type: 'ceramics',name: 'Spring4',price:'3000',location: 'img40.jpg'},
      { id:'29',type: 'ceramics',name: 'Spring4',price:'3000',location: 'img41.jpg'},
      { id:'30',type: 'ceramics',name: 'Spring4',price:'3000',location: 'img42.jpg'},
      { id:'31',type: 'ceramics',name: 'Spring4',price:'3000',location: 'img43.jpg'},
      { id:'32',type: 'ceramics',name: 'Spring4',price:'3000',location: 'img44.jpg'},
    ]
    return shopPieces;
  }
